### ISSUE TITLE
missing code; figures S1 and S2

### ISSUE THREAD

**Issue by paschatz** [paschatz/PREMON_Palm-Allometry#3]
Hey @bobmuscarella ,

I am missing the code for figures S1 and S2. Do you have it in your local repo?

Gracias 😄

**Comment by bobmuscarella** [comment]
I added it to the bottom of the analysis script.  It was back in some old code from long ago... 

I also dropped "-v2" from figures 3 and 4, and removed the note about this from the metadata.
